build:
  environment:
    php:
      version: 7.2
  nodes:
    coverage:
      tests:
        override:
        - command: phpunit --coverage-text --coverage-clover=coverage.clover
          coverage:
            file: coverage.clover   # <- Set this to where we find the coverage data.
            #    The path is relative to the current directory.
            format: clover